name: Terraform Automation


on:
  push:
    branches:
      - master/state remot file

jobs:
  terraform_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve





# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: your-region

#       - name: Build S3 Bucket and DynamoDB Table
#         run: |
#           aws s3api create-bucket --bucket your-bucket-name --region your-region
#           aws dynamodb create-table --table-name your-table-name --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST --region your-region

#       - name: Initialize Terraform Backend
#         run: |
#           terraform init -backend-config="bucket=your-bucket-name" -backend-config="dynamodb_table=your-table-name" -backend-config="region=your-region"
#           terraform apply -auto-approve

