name: Terraform Automation

# the workflow is devided into tow stadages for CI/CD
# the continuos integration tacking the code and plant
# the continuos deployment its apply to the aws account
on:
  pull_request:
    branches: # adabte your branch
      - master 
  push:
    branches: # adabte your branch
      - master 


jobs:
  terraform_plan:
    name: 'CI: planing the environment'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }} # here your are storing the IAM Role ARN in the GitHub Serets
        role-session-name: AWS-${{ github.sha }}
        aws-region: us-east-1 
        # define your egion here or make it secret
        # aws-region: ${{ secrets.AWS_REGION }}

     
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1  # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token

        
    - name: Terraform Init
      run: terraform init 
      working-directory: 

    - name: Terraform Plan
      run: terraform plan 
      working-directory: .

      
  terraform_apply:
    name: 'CD: deploying the environment to aws acc'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }} # here your are storing the IAM Role ARN in the GitHub Serets
        role-session-name: AWS-${{ github.sha }}
        aws-region: us-east-1 
        # define your egion here or make it secret
        # aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Apply
      working-directory: 
      run: |
        terraform init
        terraform apply -auto-approve
      
      