name: Terraform Automation

on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        role-session-name: AWSSession
        aws-region: us-east-1



# Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

        
    - name: Terraform Init
      run: terraform init #-backend-config="bucket=terraform-state-actions" -backend-config="key=./terraform-state-actions"
      # working-directory: state remote
      

    - name: Terraform Plan
      run: terraform plan 
      # working-directory: state remote
      
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
    #   working-directory: state remote
      
        # - name: Configure AWS credentials
        #   uses: aws-actions/configure-aws-credentials@v1
        #   with:
        #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #     aws-region: us-east-1
            