name: Terraform Automation

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      THUMBPRINT: ${{ secrets.THUMBPRINT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="github_client_id=${CLIENT_ID}" -var="github_thumbprint=${THUMBPRINT}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="github_client_id=${CLIENT_ID}" -var="github_thumbprint=${THUMBPRINT}"
